{
 "title": "2.11",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_bucket{status=\"500\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method) (rate(http_server_requests_seconds_bucket{method!=\"GET\", status=\"200\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method!=\"GET\", status=\"200\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, method) (rate(http_server_requests_seconds_bucket{method!=\"GET\", status=\"200\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (response time) max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, method) (rate(http_server_requests_seconds_bucket{method!=\"GET\", status=\"200\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(http_server_requests_seconds_bucket{method!=\"GET\", status=\"200\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}