apiVersion: v1
kind: Service
metadata:
  name: otus-dp
  labels:
    app: otus-dp
spec:
  selector:
    app: otus-dp
  ports:
    - protocol: TCP
      name: metrics
      port: 8080
      targetPort: 8080
#  type: LoadBalancer